from scratchpad import Scratchpad
from agents import ALL_AGENTS
from prompts import INPUT
import asyncio

# === 1. Initialize the Scratchpad ===
# The Scratchpad stores multiple labeled text entries to accumulate
# story elements produced by different agents in a structured format.
scratchpad = Scratchpad()

# === 2. Define mapping from agent names to scratchpad labels ===
# This dictionary maps each agent's name to a corresponding label used in the scratchpad.
AGENT_LABEL_MAP = {
    "CONFLICT": "CONFLICT",
    "CHARACTER": "CHARACTER",
    "SETTING": "SETTING",
    "PLOT": "PLOT",
    "EXPOSITION": "EXPOSITION",
    "RISING_ACTION": "RISING_ACTION",
    "CLIMAX": "CLIMAX",
    "FALLING_ACTION": "FALLING_ACTION",
    "RESOLUTION": "RESOLUTION"
}

# === 3. Define the linear execution order of agents ===
# The agents will be executed sequentially in this order to generate
# different story components from conflict to resolution.
execution_order = [
    ALL_AGENTS[0],  # CONFLICT agent
    ALL_AGENTS[1],  # CHARACTER agent
    ALL_AGENTS[2],  # SETTING agent
    ALL_AGENTS[3],  # PLOT agent
    ALL_AGENTS[4],  # EXPOSITION agent
    ALL_AGENTS[5],  # RISING_ACTION agent
    ALL_AGENTS[6],  # CLIMAX agent
    ALL_AGENTS[7],  # FALLING_ACTION agent
    ALL_AGENTS[8],  # RESOLUTION agent
]

# === 4. Helper function to extract the LLM-generated text content from agent results ===
def extract_llm_content(agent_result, agent_name) -> str:
    """
    Extracts the latest text message content generated by a specified agent from its TaskResult.
    
    Parameters:
        agent_result: The result object returned from the agent's run method, which contains multiple messages.
        agent_name: The name of the agent whose message content we want to extract.
    
    Returns:
        The content string of the latest message from the specified agent.
        If no message from the agent is found, returns the last non-user message as fallback.
        Returns an empty string if extraction fails or no valid messages exist.
    """
    try:
        # Retrieve the list of messages from the agent's result, if available
        messages = agent_result.messages if hasattr(agent_result, 'messages') else []
        
        # Iterate over messages in reverse to find the most recent from the specified agent
        for msg in reversed(messages):
            source = getattr(msg, 'source', '')
            if source.upper() == agent_name.upper():
                return getattr(msg, 'content', '')
        
        # If no exact agent message found, fallback to the last non-user message
        for msg in reversed(messages):
            source = getattr(msg, 'source', '')
            if source.lower() != 'user':
                return getattr(msg, 'content', '')
        
        # If no suitable message found, return empty string
        return ""
    except Exception as e:
        print(f"⚠️ Failed to extract LLM content: {str(e)}")
        return ""

# === 5. Main async function to run the story creation flow ===
async def run_story_flow(task: str):
    """
    Sequentially executes all agents in the predefined order, passing the cumulative
    scratchpad content as context to each agent. Collects and stores each agent's output
    back into the scratchpad. Writes intermediate results to a text file after each agent.
    
    Parameters:
        task: The initial creative writing task or prompt to begin the story generation.
    
    Returns:
        The populated Scratchpad instance containing all generated story components.
    """
    # Add the initial writing task prompt to the scratchpad
    scratchpad.add("CREATIVE WRITING TASK", task)
    print(f"\n[Creative Writing Task]\n{task}\n")

    # Execute each agent in sequence
    for agent in execution_order:
        print(f"\n=== Running {agent.name} ===")
        
        # Format the current scratchpad contents as input context for the agent
        agent_input = scratchpad.format()
        print(f"[Agent Input]\n{agent_input}\n")
        
        # Run the agent asynchronously with the current context
        response = await agent.run(task=agent_input)
        
        # Extract the textual output content from the agent's response
        output = extract_llm_content(response, agent.name)
        
        # Map agent name to scratchpad label and add the new content
        label = AGENT_LABEL_MAP.get(agent.name.upper(), agent.name)
        scratchpad.add(label, output)
        
        # Print agent output for monitoring
        print(f"[{agent.name} OUTPUT]:\n{output}\n")
        
        # Save the current scratchpad state to a file, overwriting previous
        with open("scratchpad_output.txt", "w", encoding="utf-8") as f:
            f.write(scratchpad.format())

    # Return the final scratchpad with all collected story parts
    return scratchpad

# === 6. Script entry point ===
if __name__ == "__main__":
    # Run the asynchronous story flow with the initial input prompt
    final_scratchpad = asyncio.run(run_story_flow(INPUT))

    # Print the final compiled story content from the scratchpad
    print("\n=== Final Scratchpad ===")
    print(final_scratchpad.format())
